replicaCount: 1

image:
  repository: boseabhishek/smellysearch
  pullPolicy: IfNotPresent
  tag: 0.0.1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  # -- Enable ingress controller resource
  enabled: true               # TODO: fix later 
  # -- Ingress ingressClassName
  className: nginx
  # -- Ingress annotations
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  # -- Path within the host
  path: /
  # -- List of hostnames
  hosts:
    - smelly.badgers           # TODO: fix later
  # -- TLS specification
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
